import { SkillNode } from '../types/skills';

export const SKILL_NODES: SkillNode[] = [
  // ВЕТКА: FRONTEND & UX
  {
    id: 'skill_clean_code',
    name: 'Чистая архитектура',
    nameRu: 'Чистая архитектура',
    nameEn: 'Clean Architecture',
    nameTr: 'Temiz Mimari',
    branch: 'frontend',
    icon: '✨',
    description: 'Изящный код без запахов: повышает шанс критического клика на +3%',
    descriptionRu: 'Изящный код без запахов: повышает шанс критического клика на +3%',
    descriptionEn: 'Smell-free elegant code: raises critical click chance by +3%',
    descriptionTr: 'Kokulardan arındırılmış zarif kod: kritik tıklama şansını +%3 artırır',
    maxLevel: 5,
    costPerLevel: 1,
    effectType: 'crit_chance',
    valuePerLevel: 0.03
  },
  {
    id: 'skill_hot_reload',
    name: 'Vite Fast HMR',
    nameRu: 'Vite Fast HMR',
    nameEn: 'Vite Fast HMR',
    nameTr: 'Vite Hızlı HMR',
    branch: 'frontend',
    icon: '⚡',
    description: 'Мгновенная горячая замена модулей: комбо Flow State копится на +25% быстрее',
    descriptionRu: 'Мгновенная горячая замена модулей: комбо Flow State копится на +25% быстрее',
    descriptionEn: 'Instant hot module replacement: Flow State combo charges +25% faster',
    descriptionTr: 'Anında sıcak modül değişimi: Flow State kombosu +%25 daha hızlı dolar',
    maxLevel: 3,
    costPerLevel: 1,
    effectType: 'flow_gain',
    valuePerLevel: 0.25,
    reqSkillId: 'skill_clean_code'
  },
  {
    id: 'skill_pixel_perfect',
    name: 'Pixel Perfect Eye',
    nameRu: 'Pixel Perfect точность',
    nameEn: 'Pixel Perfect Precision',
    nameTr: 'Pixel Perfect Hassasiyeti',
    branch: 'frontend',
    icon: '🎯',
    description: 'Точность верстки до субпикселя: увеличивает множитель крита на +1.0x',
    descriptionRu: 'Точность верстки до субпикселя: увеличивает множитель крита на +1.0x',
    descriptionEn: 'Subpixel layout precision: increases crit multiplier by +1.0x',
    descriptionTr: 'Alt piksel düzeyinde düzen hassasiyeti: kritik çarpanını +1.0x artırır',
    maxLevel: 4,
    costPerLevel: 2,
    effectType: 'crit_power',
    valuePerLevel: 1.0,
    reqSkillId: 'skill_clean_code'
  },
  {
    id: 'skill_wasm_speed',
    name: 'WebAssembly Core',
    nameRu: 'Ядро WebAssembly',
    nameEn: 'WebAssembly Core',
    nameTr: 'WebAssembly Çekirdeği',
    branch: 'frontend',
    icon: '🚀',
    description: 'Бинарная скорость нативного кода: криты наносят еще на +1.5x больше кода',
    descriptionRu: 'Бинарная скорость нативного кода: криты наносят еще на +1.5x больше кода',
    descriptionEn: 'Native binary speed: critical clicks generate an extra +1.5x code',
    descriptionTr: 'Yerel ikili hız: kritik tıklamalar fazladan +1.5x kod üretir',
    maxLevel: 3,
    costPerLevel: 3,
    effectType: 'crit_power',
    valuePerLevel: 1.5,
    reqSkillId: 'skill_pixel_perfect'
  },

  // ВЕТКА: BACKEND & DEVOPS
  {
    id: 'skill_async_io',
    name: 'Асинхронный Event Loop',
    nameRu: 'Асинхронный Event Loop',
    nameEn: 'Async Event Loop',
    nameTr: 'Asenkron Event Loop',
    branch: 'backend',
    icon: '🔄',
    description: 'Неблокирующий ввод-вывод: весь пассивный доход C#/сек вырастает на +20%',
    descriptionRu: 'Неблокирующий ввод-вывод: весь пассивный доход C#/сек вырастает на +20%',
    descriptionEn: 'Non-blocking I/O: passive C#/sec generation increases by +20%',
    descriptionTr: 'Engellenmeyen G/Ç: pasif C#/sn üretimi +%20 artar',
    maxLevel: 5,
    costPerLevel: 1,
    effectType: 'passive_boost',
    valuePerLevel: 0.20
  },
  {
    id: 'skill_redis_cache',
    name: 'Redis In-Memory Cache',
    nameRu: 'Кэш Redis In-Memory',
    nameEn: 'Redis In-Memory Cache',
    nameTr: 'Redis Bellek İçi Önbellek',
    branch: 'backend',
    icon: '⚡',
    description: 'Кэш в оперативной памяти: сокращает перезарядку Time Warp на 15%',
    descriptionRu: 'Кэш в оперативной памяти: сокращает перезарядку Time Warp на 15%',
    descriptionEn: 'In-memory caching: reduces Time Warp cooldown by 15%',
    descriptionTr: 'Bellek içi önbellekleme: Zaman Bükülmesi bekleme süresini %15 azaltır',
    maxLevel: 3,
    costPerLevel: 2,
    effectType: 'timewarp_cdr',
    valuePerLevel: 0.15,
    reqSkillId: 'skill_async_io'
  },
  {
    id: 'skill_k8s_autoscaling',
    name: 'Kubernetes Автоскейлинг',
    nameRu: 'Kubernetes Автоскейлинг',
    nameEn: 'Kubernetes Autoscaling',
    nameTr: 'Kubernetes Otomatik Ölçekleme',
    branch: 'backend',
    icon: '☸️',
    description: 'Оркестрация микросервисов: буст пассивного кода студии еще на +35%',
    descriptionRu: 'Оркестрация микросервисов: буст пассивного кода студии еще на +35%',
    descriptionEn: 'Microservice orchestration: boosts passive studio code by +35%',
    descriptionTr: 'Mikroservis orkestrasyonu: pasif stüdyo kodunu +%35 artırır',
    maxLevel: 4,
    costPerLevel: 2,
    effectType: 'passive_boost',
    valuePerLevel: 0.35,
    reqSkillId: 'skill_async_io'
  },
  {
    id: 'skill_quantum_threads',
    name: 'Квантовая многопоточность',
    nameRu: 'Квантовая многопоточность',
    nameEn: 'Quantum Multithreading',
    nameTr: 'Kuantum Çoklu İş Parçacığı',
    branch: 'backend',
    icon: '⚛️',
    description: 'Суперпозиция потоков: сверх-буст пассивного кода C#/сек на +50%',
    descriptionRu: 'Суперпозиция потоков: сверх-буст пассивного кода C#/сек на +50%',
    descriptionEn: 'Thread superposition: ultra boost to passive C#/sec by +50%',
    descriptionTr: 'İş parçacığı süperpozisyonu: pasif C#/sn üretimini +%50 artırır',
    maxLevel: 3,
    costPerLevel: 3,
    effectType: 'passive_boost',
    valuePerLevel: 0.50,
    reqSkillId: 'skill_k8s_autoscaling'
  },

  // ВЕТКА: STARTUP MANAGEMENT & BUSINESS
  {
    id: 'skill_negotiation',
    name: 'Искусство питчинга',
    nameRu: 'Искусство питчинга',
    nameEn: 'Pitching Mastery',
    nameTr: 'Sunum ve Pazarlık Ustalığı',
    branch: 'business',
    icon: '🤝',
    description: 'Договоренности с вендорами: скидка на все улучшения в магазине 5%',
    descriptionRu: 'Договоренности с вендорами: скидка на все улучшения в магазине 5%',
    descriptionEn: 'Vendor bargaining: 5% discount across all shop upgrades',
    descriptionTr: 'Tedarikçi pazarlığı: mağazadaki tüm yükseltmelerde %5 indirim',
    maxLevel: 5,
    costPerLevel: 1,
    effectType: 'shop_discount',
    valuePerLevel: 0.05
  },
  {
    id: 'skill_bug_bounty_hunter',
    name: 'Bug Bounty Охотник',
    nameRu: 'Bug Bounty Охотник',
    nameEn: 'Bug Bounty Hunter',
    nameTr: 'Bug Bounty Avcısı',
    branch: 'business',
    icon: '🐞',
    description: 'Выплаты за уязвимости: за поимку багов в коде дается на +50% больше строк',
    descriptionRu: 'Выплаты за уязвимости: за поимку багов в коде дается на +50% больше строк',
    descriptionEn: 'Vulnerability bounties: squashing bugs awards +50% more code lines',
    descriptionTr: 'Güvenlik açığı ödülleri: kod hatalarını ayıklamak +%50 daha fazla kod kazandırır',
    maxLevel: 3,
    costPerLevel: 1,
    effectType: 'bug_reward_boost',
    valuePerLevel: 0.50,
    reqSkillId: 'skill_negotiation'
  },
  {
    id: 'skill_venture_network',
    name: 'Венчурные связи',
    nameRu: 'Венчурные связи',
    nameEn: 'Venture Network',
    nameTr: 'Girişim Sermayesi Ağı',
    branch: 'business',
    icon: '💼',
    description: 'Инвестиции бизнес-ангелов: постоянный бонус +25% ко всем доходам в рублях ₽',
    descriptionRu: 'Инвестиции бизнес-ангелов: постоянный бонус +25% ко всем доходам в рублях ₽',
    descriptionEn: 'Angel investments: permanent +25% boost to all revenue income',
    descriptionTr: 'Melek yatırımcılar: tüm gelirlere kalıcı +%25 gelir artışı',
    maxLevel: 4,
    costPerLevel: 2,
    effectType: 'money_boost',
    valuePerLevel: 0.25,
    reqSkillId: 'skill_negotiation'
  },
  {
    id: 'skill_unicorn_status',
    name: 'Статус IT-Единорога',
    nameRu: 'Статус IT-Единорога',
    nameEn: 'Unicorn Status',
    nameTr: 'IT-Unicorn Statüsü',
    branch: 'business',
    icon: '🦄',
    description: 'Оценка стартапа в $1 млрд: еще -8% скидки на оборудование и +40% к деньгам',
    descriptionRu: 'Оценка стартапа в $1 млрд: еще -8% скидки на оборудование и +40% к деньгам',
    descriptionEn: '$1B startup valuation: extra -8% gear discount and +40% revenue boost',
    descriptionTr: '1 milyar dolar değerleme: ekstra -%8 ekipman indirimi ve +%40 gelir artışı',
    maxLevel: 3,
    costPerLevel: 3,
    effectType: 'money_boost',
    valuePerLevel: 0.40,
    reqSkillId: 'skill_venture_network'
  },

  // ВЕТКА: AI & НЕЙРОСЕТИ
  {
    id: 'skill_prompt_engineering',
    name: 'Промпт-инжиниринг LLM',
    nameRu: 'Промпт-инжиниринг LLM',
    nameEn: 'Prompt Engineering LLM',
    nameTr: 'LLM Prompt Mühendisliği',
    branch: 'ai',
    icon: '💬',
    description: 'Ювелирные промпты: нейросети ускоряют генерацию кода за клик на +20%',
    descriptionRu: 'Ювелирные промпты: нейросети ускоряют генерацию кода за клик на +20%',
    descriptionEn: 'Precision prompting: LLMs boost code per click by +20%',
    descriptionTr: 'Hassas yönlendirme: büyük dil modelleri tıklama başına kodu +%20 artırır',
    maxLevel: 5,
    costPerLevel: 1,
    effectType: 'click_boost',
    valuePerLevel: 0.20
  },
  {
    id: 'skill_ai_agents',
    name: 'Мультиагентный рой',
    nameRu: 'Мультиагентный рой',
    nameEn: 'Multi-Agent Swarm',
    nameTr: 'Çoklu Ajan Sürüsü',
    branch: 'ai',
    icon: '🤖',
    description: 'Сотни микроагентов автономно пишут фичи: пассивный доход C#/сек +40%',
    descriptionRu: 'Сотни микроагентов автономно пишут фичи: пассивный доход C#/сек +40%',
    descriptionEn: 'Autonomous micro-agents ship features: passive C#/sec +40%',
    descriptionTr: 'Otonom mikro ajanlar özellikleri kodlar: pasif C#/sn +%40',
    maxLevel: 4,
    costPerLevel: 2,
    effectType: 'passive_boost',
    valuePerLevel: 0.40,
    reqSkillId: 'skill_prompt_engineering'
  },
  {
    id: 'skill_fine_tuning',
    name: 'LoRA & Файн-тюнинг весов',
    nameRu: 'LoRA & Файн-тюнинг весов',
    nameEn: 'LoRA & Weights Fine-Tuning',
    nameTr: 'LoRA ve İnce Ayar',
    branch: 'ai',
    icon: '🧠',
    description: 'Кастомные веса модели: шанс критического клика +5% и множитель +2.0x',
    descriptionRu: 'Кастомные веса модели: шанс критического клика +5% и множитель +2.0x',
    descriptionEn: 'Custom model weights: crit chance +5% and multiplier +2.0x',
    descriptionTr: 'Özel model ağırlıkları: kritik şansı +%5 ve çarpan +2.0x',
    maxLevel: 3,
    costPerLevel: 3,
    effectType: 'crit_chance',
    valuePerLevel: 0.05,
    reqSkillId: 'skill_ai_agents'
  },
  {
    id: 'skill_agi_singularity',
    name: 'AGI Сингулярность',
    nameRu: 'AGI Сингулярность',
    nameEn: 'AGI Singularity',
    nameTr: 'AGI Tekilliği',
    branch: 'ai',
    icon: '🌟',
    description: 'Искусственный общий интеллект: грандиозный буст всего прогресса студии x2.5!',
    descriptionRu: 'Искусственный общий интеллект: грандиозный буст всего прогресса студии x2.5!',
    descriptionEn: 'Artificial General Intelligence: monumental x2.5 boost to all progress!',
    descriptionTr: 'Yapay Genel Zeka: tüm stüdyo ilerlemesine devasa x2.5 artış!',
    maxLevel: 2,
    costPerLevel: 5,
    effectType: 'singularity',
    valuePerLevel: 1.5,
    reqSkillId: 'skill_fine_tuning'
  },

  // ВЕТКА: DEVOPS & CI/CD
  {
    id: 'skill_gitops',
    name: 'GitOps & Trunk-Based Dev',
    nameRu: 'GitOps & Trunk-Based Dev',
    nameEn: 'GitOps & Trunk-Based Dev',
    nameTr: 'GitOps ve Trunk Tabanlı Geliştirme',
    branch: 'devops',
    icon: '🔀',
    description: 'Непрерывная интеграция: слияние Pull Request приносит на +50% больше денег ₽ и кода',
    descriptionRu: 'Непрерывная интеграция: слияние Pull Request приносит на +50% больше денег ₽ и кода',
    descriptionEn: 'Continuous integration: PR merges award +50% more revenue and code',
    descriptionTr: 'Sürekli entegrasyon: PR birleştirmeleri +%50 daha fazla gelir ve kod kazandırır',
    maxLevel: 5,
    costPerLevel: 1,
    effectType: 'pr_boost',
    valuePerLevel: 0.50
  },
  {
    id: 'skill_github_actions',
    name: 'GitHub Actions Matrix',
    nameRu: 'GitHub Actions Matrix',
    nameEn: 'GitHub Actions Matrix',
    nameTr: 'GitHub Actions Matrisi',
    branch: 'devops',
    icon: '⚙️',
    description: 'Автоматизированный CI/CD: ускоряет пайплайн тестов и увеличивает награду за Broken Build на +50%',
    descriptionRu: 'Автоматизированный CI/CD: ускоряет пайплайн тестов и увеличивает награду за Broken Build на +50%',
    descriptionEn: 'Automated CI/CD: accelerates test pipelines and increases Broken Build reward by +50%',
    descriptionTr: 'Otomatik CI/CD: testleri hızlandırır ve Hatalı Yapı düzeltme ödülünü +%50 artırır',
    maxLevel: 4,
    costPerLevel: 2,
    effectType: 'pipeline_haste',
    valuePerLevel: 0.50,
    reqSkillId: 'skill_gitops'
  },
  {
    id: 'skill_blitz_compiler',
    name: 'LLVM JIT-Оптимизатор',
    nameRu: 'LLVM JIT-Оптимизатор',
    nameEn: 'LLVM JIT Optimizer',
    nameTr: 'LLVM JIT Optimize Edici',
    branch: 'devops',
    icon: '⚡',
    description: 'Векторизация машинного кода: продлевает действие 10x Refactor Blitz на +5 секунд за уровень',
    descriptionRu: 'Векторизация машинного кода: продлевает действие 10x Refactor Blitz на +5 секунд за уровень',
    descriptionEn: 'Machine code vectorization: extends 10x Refactor Blitz duration by +5s per level',
    descriptionTr: 'Makine kodu vektörizasyonu: 10x Refactor Blitz süresini seviye başına +5sn uzatır',
    maxLevel: 3,
    costPerLevel: 2,
    effectType: 'blitz_duration',
    valuePerLevel: 5,
    reqSkillId: 'skill_gitops'
  },
  {
    id: 'skill_auto_deploy',
    name: 'Zero-Downtime Blue-Green',
    nameRu: 'Zero-Downtime Blue-Green',
    nameEn: 'Zero-Downtime Blue-Green',
    nameTr: 'Kesintisiz Blue-Green Dağıtım',
    branch: 'devops',
    icon: '🚀',
    description: 'Бесшовный автодеплой без простоя: пассивный доход +30% и дивиденд при каждом успешном билде',
    descriptionRu: 'Бесшовный автодеплой без простоя: пассивный доход +30% и дивиденд при каждом успешном билде',
    descriptionEn: 'Seamless zero-downtime deploy: +30% passive income and dividend per green build',
    descriptionTr: 'Kesintisiz otomatik dağıtım: +%30 pasif gelir ve her yeşil derlemede temettü',
    maxLevel: 3,
    costPerLevel: 3,
    effectType: 'passive_boost',
    valuePerLevel: 0.30,
    reqSkillId: 'skill_github_actions'
  }
];
